<?php


## sds installation variables
## this file was autogenerated, please do not edit by hand
## use the script
define ('SDS_HOME_URL', getenv('REMOTE_ADDR'));
define ('SDS_LOGIN_URL', getenv('SDS_LOGIN_URL'));
define ('SDS_AUTO_LOGIN_URL',  getenv('SDS_AUTO_LOGIN_URL'));
//define ('SDS_BASE', "/var/www/html/sds");
//define ('SDS_BASE_URL', "https://simmons.mit.edu/sds/");
define ('SDS_COOKIE_PATH',  getenv('SDS_COOKIE_PATH'));
define ('SDB_DATABASE', getenv('SDB_DATABASE'));
//define ('SDB_PASSWORD_FILE', "/var/www/sds/sdb-passwd-apache-without-dbname");
//define ('SDS_QUERY_LOG', "/var/www/sds/log/querylogs/sds");

?>
